include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

build-docker-image:
  extends: .build-docker-image

goreleaser-snapshot:
  extends: .compute-ci.goreleaser-snapshot

e2e-test:
  extends: .compute-ci.goreleaser-snapshot
  stage: verify
  before_script:
  - |
    curl -L -o /tmp/kubeclient.tgz https://github.com/DataDog/kubernetes/releases/download/v1.31.2-dd.1/kubernetes-client-linux-arm64.tar.gz 
    tar  xzf /tmp/kubeclient.tgz -C /usr/local/bin/ kubernetes/client/bin/kubectl --strip-components=3
  script:
  - ./.ci/setup-kind.sh
  - ./.ci/setup-e2e.sh
  - ./.ci/run-e2e.sh
  artifacts:
    paths:
    - .ci/kind.env

goreleaser:
  extends: .compute-ci.goreleaser

# Make sure to delete the kind cluster.
# Not sure this is really needed?
kube-sync.on-failure:
  extends: on-failure
  when: always
  script:
  -  source .ci/kind.env && kind delete cluster --name $KIND_CLUSTER_NAME